name = "a-person-said-a-thing"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "apst-quotes"
database_id = "66490aff-509c-4bfe-8ddb-8751f16b64de"

# R2 Bucket binding (for thumbnail uploads)
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "apst-thumbnails"
