name = "a-person-said-a-thing"
main = "_worker.js"
compatibility_date = "2025-09-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./"

[[d1_databases]]
binding = "DB"
database_name = "apst-quotes"
database_id = "66490aff-509c-4bfe-8ddb-8751f16b64de"
